services:

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: sb_kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - kuma_data:/app/data
    deploy:
      resources:
        limits:
          memory: 512m

  dockhand:
    image: fnsys/dockhand:latest
    container_name: sb_dockhand
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://${DOCKHAND_DB_USER}:${DOCKHAND_DB_PASS}@192.168.0.210:5432/dockhand
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    deploy:
      resources:
        limits:
          memory: 256m

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: sb_homepage
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: America/Sao_Paulo
      HOMEPAGE_ALLOWED_HOSTS: 192.168.0.216:3002,home.joaopaulo.me
      PROXMOX_TOKEN_ID: ${PROXMOX_TOKEN_ID}
      PROXMOX_TOKEN_SECRET: ${PROXMOX_TOKEN_SECRET}
    deploy:
      resources:
        limits:
          memory: 256m

volumes:
  kuma_data:
  dockhand_data:
